### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by vin111** [karthicksivakumar191194/larasnap#1]
Error:
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [login] not defined.

Environment information
Laravel version
7.26.0
Laravel locale
en
Laravel config cached
true
PHP version
7.3.14

![image](https://user-images.githubusercontent.com/25017968/91332167-0d421280-e7cc-11ea-9fd4-207c100307e8.png)

**Comment by karthicksivakumar191194** [comment]
@vin111 

Have u installed laravel authentication package(laravel/ui) before installing LaraSnap.

Check the **Installation > Step Two** section on our official docs https://karthicksivakumar191194.github.io/larasnap/ 

Let us know if you still face any challenges on package installation.

**Comment by lalaland412** [comment]
🚩🚩🚩
